#http://127.0.0.1:8000
#mkdocs serve
site_name: PROMOTE Analysis Sprint
theme: minty
site_url: https://promote-project.github.io/promote_analysis_sprint_2026/
#repo_name: promote-project.github.io/promote_analysis_sprint_2026
#repo_url: https://github.com/promote-project.github.io/promote_analysis_sprint_2026

extra_css:
  - extra.css

nav:
  - Home: index.md
  - Schedule: schedule.md
  - Datasets: datasets.md
  - Get ready: get_ready.md
#  - FAQ: FAQ.md

extra_files:
  - images/

markdown_extensions:
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - footnotes
  - pymdownx.emoji
  - attr_list
